title: Blog
logo: /assets/images/logos/github.svg
# name: Final Blog
email: 569553292@qq.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  extensions:
    - autolink
    - footnotes
    - smart
theme: minima
encoding: UTF-8

sass:
  sass_dir: _sass
  style: compressed
# Plugins
plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
collections_dir: pages
collections:
  esl:
    output: true
defaults:
  - scope:
      path: ""
    values:
      layout: post
      output: true
      sidebar: true
      author: ilikly
      type: post
      mark:
        pin: false
        hot: false
      banner: https://source.unsplash.com/random/800x400
exclude:
  - .idea/